### ISSUE TITLE
3-5 Weeks NO sync

### ISSUE THREAD

**Issue by gator6615** [Sandokaaan/Earthcoin#1]

**Comment by Sandokaaan** [comment]
It is strange. First, please check your firewall to see if it is blocking your connection. You can also use the command 
<code>addnode [IP_OF_SOME_NODE] add </code>
to add some nodes IP addresses to your EAC daemon/wallet.
List of active nodes can be seen on the block explorer
<code>https://chainz.cryptoid.info/eac/#!network</code>

Example:
<code>addnode 42.61.91.90 add</code>
