### ISSUE TITLE
The calling parameters of getearthcoinblocksubsidiary function are inconsistent

### ISSUE THREAD

**Issue by eacsuite** [Sandokaaan/Earthcoin#2]
Compilation error:

The calling parameters of getearthcoinblocksubsidiary function are inconsistent

The error prompt is as follows:

  CXX      test/test_test_earthcoin-earthcoin_tests.o
test/earthcoin_tests.cpp: In member function ‘void earthcoin_tests::subsidy_limit_test::test_method()’:
test/earthcoin_tests.cpp:71:78: error: too many arguments to function ‘CAmount GetEarthcoinBlockSubsidy(int, const Consensus::Params&)’
         CAmount nSubsidy = GetEarthcoinBlockSubsidy(nHeight, params, prevHash);
                                                                              ^
In file included from test/earthcoin_tests.cpp:7:0:
./earthcoin.h:10:9: note: declared here
 CAmount GetEarthcoinBlockSubsidy(int nHeight, const Consensus::Params& consensusParams);

**Comment by Sandokaaan** [comment]
Thank you for the warning. Fixed now in the devel branch.
