### ISSUE TITLE
The calling parameters of GenerateCoinbaseCommitment function are inconsistent

### ISSUE THREAD

**Issue by eacsuite** [Sandokaaan/Earthcoin#3]
Compilation error:

The calling parameters of GenerateCoinbaseCommitment function are inconsistent

The error prompt is as follows:

  CXX      libearthcoin_server_a-miner.o
miner.cpp: In member function ‘std::unique_ptr<CBlockTemplate> BlockAssembler::CreateNewBlock(const CScript&, bool)’:
miner.cpp:173:129: error: too many arguments to function ‘std::vector<unsigned char> GenerateCoinbaseCommitment(CBlock&, const CBlockIndex*, const Consensus::Params&)’
     pblocktemplate->vchCoinbaseCommitment = GenerateCoinbaseCommitment(*pblock, pindexPrev, chainparams.GetConsensus(), prevHash);
                                                                                                                                 ^
In file included from ./miner.h:11:0,
                 from miner.cpp:6:
./validation.h:420:28: note: declared here
 std::vector<unsigned char> GenerateCoinbaseCommitment(CBlock& block, const CBlockIndex* pindexPrev, const Consensus::Params& consensusParams);

**Comment by Sandokaaan** [comment]
There is no such error in the code. Probably fixed earlier. Thanks.
